### ISSUE TITLE
Liste için site önerileri

### ISSUE THREAD

**Issue by lazjedi** [Raidware/ublacklist-turkish#1]
Kaynak belirtemediğim için pull request oluşturamadım. Kişisel listemi buradan paylaşmak durumundayım.

```
*://www.aksam.com.tr/*
*://www.aydinlik.com.tr/*
*://www.birgun.net/*
*://www.cumhuriyet.com.tr/*
*://www.dunya.com/*
*://www.fanatik.com.tr/*
*://www.fotomac.com.tr/*
*://www.fotospor.com/*
*://www.gazetevatan.com/*
*://www.gunes.com/*
*://www.haber7.com/*
*://www.haberler.com/*
*://www.haberturk.com/*
*://www.karar.com/*
*://www.medyaradar.com/*
*://www.milligazete.com.tr/*
*://www.milliyet.com.tr/*
*://www.posta.com.tr/*
*://www.sabah.com.tr/*
*://www.sozcu.com.tr/*
*://www.sporx.com/*
*://www.star.com.tr/*
*://www.takvim.com.tr/*
*://www.turkiyenewspaper.com/*
*://www.yeniakit.com.tr/*
*://www.yenicaggazetesi.com.tr/*
*://www.yenisafak.com/*
*://www.cnnturk.com/*
*://www2.odatv.com/*
*://www.ntv.com.tr/*
*://www.ensonhaber.com/*
*://www.sondakika.com/*
*://www.ahaber.com.tr/*
*://trthaber.com/*
*://otomobil.haber7.com/*
*://bigpara.hurriyet.com.tr/*
*://uzmanpara.milliyet.com.tr/*
*://onedio.com/*
*://finans.mynet.com/*
*://ekonomi.haber7.com/*
*://odatv4.com/*
*://www.acunn.com/*
*://www.internethaber.com/*
*://www.gazeteduvar.com.tr/*
*://www.haber61.net/*
*://habersizseniz.com/*
*://www.mynet.com/*
*://www.superhaber.tv/*
*://m.bloomberght.com/*
*://ajansspor.com/*
*://haberglobal.com.tr/*
*://www.evrensel.net/*
*://www.aktifhaber.com/*
*://www.haber3.com/*
*://www.tgrthaber.com.tr/*
*://www.aspor.com.tr/*
*://www.turkiyegazetesi.com.tr/*
*://www.iha.com.tr/*
*://finans.gazetevatan.com/*
*://www.ulusal.com.tr/*
*://www.konhaber.com/*
*://www.hurriyet.com.tr/*
*://m.yeniakit.com.tr/*
*://www.trthaber.com/*
*://edirnejethaber.com/*
*://tele1.com.tr/*
*://www.yenialanya.com/*
*://yenisokegazetesi.com/*
*://spor.haber7.com/*
*://www.memurlar.net/*
*://www.mackolik.com/*
*://www.ntvspor.net/*
*://beinsports.com.tr/*
*://medyascope.tv/*
*://www.diyanethaber.com.tr/*
*://www.haberay.com/*
*://www.sahibinden.com/*
*://yeniyasamgazetesi5.com/*
*://www.arabam.com/*
*://www.ekonomim.com/*
*://artigercek.com/*
*://yenigungazete.com/*
*://www.odatv.com/*
*://www.bursadabiz.com/*
*://www.msn.com/*
*://serbestiyet.com/*
*://www.malatyaguncel.com/*
*://www.gercekgundem.com/*
*://www.haber24.com.tr/*
*://www.apara.com.tr/*
*://www.yesilgiresun.com.tr/*
```

**Comment by Raidware** [comment]
> Kaynak belirtemediğim için pull request oluşturamadım. Kişisel listemi buradan paylaşmak durumundayım.
> 
> ```
> *://www.aksam.com.tr/*
> *://www.aydinlik.com.tr/*
> *://www.birgun.net/*
> *://www.cumhuriyet.com.tr/*
> *://www.dunya.com/*
> *://www.fanatik.com.tr/*
> *://www.fotomac.com.tr/*
> *://www.fotospor.com/*
> *://www.gazetevatan.com/*
> *://www.gunes.com/*
> *://www.haber7.com/*
> *://www.haberler.com/*
> *://www.haberturk.com/*
> *://www.karar.com/*
> *://www.medyaradar.com/*
> *://www.milligazete.com.tr/*
> *://www.milliyet.com.tr/*
> *://www.posta.com.tr/*
> *://www.sabah.com.tr/*
> *://www.sozcu.com.tr/*
> *://www.sporx.com/*
> *://www.star.com.tr/*
> *://www.takvim.com.tr/*
> *://www.turkiyenewspaper.com/*
> *://www.yeniakit.com.tr/*
> *://www.yenicaggazetesi.com.tr/*
> *://www.yenisafak.com/*
> *://www.cnnturk.com/*
> *://www2.odatv.com/*
> *://www.ntv.com.tr/*
> *://www.ensonhaber.com/*
> *://www.sondakika.com/*
> *://www.ahaber.com.tr/*
> *://trthaber.com/*
> *://otomobil.haber7.com/*
> *://bigpara.hurriyet.com.tr/*
> *://uzmanpara.milliyet.com.tr/*
> *://onedio.com/*
> *://finans.mynet.com/*
> *://ekonomi.haber7.com/*
> *://odatv4.com/*
> *://www.acunn.com/*
> *://www.internethaber.com/*
> *://www.gazeteduvar.com.tr/*
> *://www.haber61.net/*
> *://habersizseniz.com/*
> *://www.mynet.com/*
> *://www.superhaber.tv/*
> *://m.bloomberght.com/*
> *://ajansspor.com/*
> *://haberglobal.com.tr/*
> *://www.evrensel.net/*
> *://www.aktifhaber.com/*
> *://www.haber3.com/*
> *://www.tgrthaber.com.tr/*
> *://www.aspor.com.tr/*
> *://www.turkiyegazetesi.com.tr/*
> *://www.iha.com.tr/*
> *://finans.gazetevatan.com/*
> *://www.ulusal.com.tr/*
> *://www.konhaber.com/*
> *://www.hurriyet.com.tr/*
> *://m.yeniakit.com.tr/*
> *://www.trthaber.com/*
> *://edirnejethaber.com/*
> *://tele1.com.tr/*
> *://www.yenialanya.com/*
> *://yenisokegazetesi.com/*
> *://spor.haber7.com/*
> *://www.memurlar.net/*
> *://www.mackolik.com/*
> *://www.ntvspor.net/*
> *://beinsports.com.tr/*
> *://medyascope.tv/*
> *://www.diyanethaber.com.tr/*
> *://www.haberay.com/*
> *://www.sahibinden.com/*
> *://yeniyasamgazetesi5.com/*
> *://www.arabam.com/*
> *://www.ekonomim.com/*
> *://artigercek.com/*
> *://yenigungazete.com/*
> *://www.odatv.com/*
> *://www.bursadabiz.com/*
> *://www.msn.com/*
> *://serbestiyet.com/*
> *://www.malatyaguncel.com/*
> *://www.gercekgundem.com/*
> *://www.haber24.com.tr/*
> *://www.apara.com.tr/*
> *://www.yesilgiresun.com.tr/*
> ```

cumhuriyet ve sahibinden vb siteleri engelleme sebebini soyler misiniz?

**Comment by lazjedi** [comment]
> cumhuriyet ve sahibinden vb siteleri engelleme sebebini soyler misiniz?

Cumhuriyet gazetesi de diğerleri gibi clickbait ve bomboş haberler yapan bir site. Arama sonuçlarımı kirlettiği için kara listeye aldım. Sahibinden de aynı şekilde. Herhangi bir arabayı araştırırken spam yapar gibi tüm sonuçları kaplıyor. Doğru ve temiz bilgiye ulaşmamı engelleyen virüs gibi bir site Sahibinden.

**Comment by Raidware** [comment]
eklenmiştir
